/* projects.js — Portfolio Projects Data */

export const PROJECT_STATUSES = ['Planning', 'Simulation', 'Building', 'Testing', 'Deployed'];

export const DEFAULT_PROJECTS = [
  {
    id: 'p0',
    phase: 0,
    title: 'Python Tools Suite',
    subtitle: 'Subnet Scanner + File Organizer',
    description: 'Build two Python CLI tools from scratch: a network subnet scanner (using socket/scapy) and an intelligent file organizer. Demonstrates OOP, data structures, and real-world utility.',
    skills: ['Python OOP', 'Networking Basics', 'File I/O', 'CLI Design', 'Git'],
    statusIndex: 0,
    githubUrl: '',
    notes: '',
    startedAt: null,
    deployedAt: null,
    xp: 300,
  },
  {
    id: 'p1',
    phase: 1,
    title: '2-DOF Planar Arm Solver',
    subtitle: 'FK/IK in Pure Python — No Libraries',
    description: 'Implement forward and inverse kinematics for a 2-joint planar robotic arm from scratch using only Python + NumPy. No Robotics Toolbox. Just math + code + visualization.',
    skills: ['Linear Algebra', 'Kinematics', 'Python NumPy', 'Matplotlib', 'DH Parameters'],
    statusIndex: 0,
    githubUrl: '',
    notes: '',
    startedAt: null,
    deployedAt: null,
    xp: 500,
  },
  {
    id: 'p2',
    phase: 2,
    title: 'Autonomous Warehouse Robot',
    subtitle: 'Gazebo + Nav2 + SLAM — Full Sim',
    description: 'Build a complete Gazebo Harmonic warehouse world with shelves and obstacles. Deploy TurtleBot3 with slam_toolbox to map the space, then Nav2 to navigate autonomously from point A to B.',
    skills: ['Gazebo Harmonic', 'Nav2', 'SLAM Toolbox', 'ROS2 Jazzy', 'SDF World Design', 'Behavior Trees'],
    statusIndex: 0,
    githubUrl: '',
    notes: '',
    startedAt: null,
    deployedAt: null,
    xp: 750,
  },
  {
    id: 'p3',
    phase: 3,
    title: 'Physical Differential Drive Robot',
    subtitle: 'Fusion360 → 3D Print → SLAM → Nav2',
    description: 'Design chassis in Fusion360, export URDF, 3D print, wire up RPi 4 + RPLiDAR + ESP32 + L298N, deploy ROS2 Jazzy. Map a room with slam_toolbox, navigate autonomously with Nav2.',
    skills: ['Fusion360', 'URDF', '3D Printing', 'micro-ROS', 'RPi4', 'Electronics Wiring', 'SLAM', 'Nav2'],
    statusIndex: 0,
    githubUrl: '',
    notes: '',
    startedAt: null,
    deployedAt: null,
    xp: 1200,
  },
  {
    id: 'p4',
    phase: 4,
    title: 'Specialization Capstone',
    subtitle: 'Your chosen lane — deep expertise proof',
    description: 'The capstone project matching your specialization lane. Industrial: ROS2 ↔ OPC-UA bridge. AMR: 3-robot coordinated fleet. Aerial: autonomous waypoint drone. Medical: compliant manipulation arm.',
    skills: ['Lane-specific', 'Advanced ROS2', 'Production deployment', 'Documentation'],
    statusIndex: 0,
    githubUrl: '',
    notes: '',
    startedAt: null,
    deployedAt: null,
    xp: 2000,
  },
];
